const clubesDoCoracao = [
    {
        nome: 'Fúria',
        id: 'furia',
        regiao: 'br',
        abreviacao: 'fur',
        enderecoImagem: 'https://img-cdn.hltv.org/teamlogo/mvNQc4csFGtxXk5guAh8m1.svg?ixlib=java-2.1.0&s=11e5056829ad5d6c06c5961bbe76d20c',
        elenco: [
            {
                nome: 'Yuri Santos',
                nick: 'yuurih',
                imagem: 'https://img-cdn.hltv.org/playerbodyshot/tLPRhHe16F0Ujp5obg659F.png?ixlib=java-2.1.0&w=400&s=92ed522f480b8cba167e13025e6bb88b',
                nomeENick: 'Yuri “yuurih” Santos',
            },
            {
                nome: 'Kaike Cerato',
                nick: 'KSCERATO',
                imagem: 'https://img-cdn.hltv.org/playerbodyshot/QSap61dukav1leU8Tpqrjq.png?ixlib=java-2.1.0&w=400&s=d19ff24fe1fd5627aa433f2ff496e5c9',
                nomeENick: 'Kaike “KSCERATO” Cerato',
            },
            {
                nome: 'Gabriel Toledo',
                nick: 'FalleN',
                imagem: 'https://img-cdn.hltv.org/playerbodyshot/VOnNQs64vdjfYEHMNSBeyD.png?ixlib=java-2.1.0&w=400&s=ca1ba5963f2eddf0b41149aed0d34ae1',
                nomeENick: 'Gabriel “FalleN” Toledo',
            },
            {
                nome: 'Danil Golubenko',
                nick: 'molodoy',
                imagem: 'https://img-cdn.hltv.org/playerbodyshot/LAYT8z3prNmvldBnptJFOs.png?ixlib=java-2.1.0&w=400&s=7744d5f2c87beb48b4dddf30e8515d36',
                nomeENick: 'Danil “molodoy” Golubenko',
            },
            {
                nome: 'Mareks Gaļinskis',
                nick: 'YEKINDAR',
                imagem: 'https://img-cdn.hltv.org/playerbodyshot/dpzRR_cteaS91XhJF5vtR8.png?ixlib=java-2.1.0&w=400&s=cf94c66497a118cf779965535f199469',
                nomeENick: 'Mareks “YEKINDAR” Gaļinskis',
            },
            {
                nome: 'Sid Macedo',
                nick: 'sidde',
                imagem: 'https://img-cdn.hltv.org/playerbodyshot/sa8vSue8dW_VTnLrnS4uV-.png?ixlib=java-2.1.0&w=400&s=2b5993d319e8e2bee48cc055d6dd5ff7',
                nomeENick: 'Sid “sidde” Macedo',
            },
        ],
    },
    {
        nome: 'Imperial',
        id: 'imperial',
        regiao: 'br',
        abreviacao: 'imp',
        enderecoImagem: 'https://img-cdn.hltv.org/teamlogo/WF5P55R5fxcmhoew6vHZQr.png?ixlib=java-2.1.0&w=100&s=69a1bfb54d6350db4a0b18ff87a96dcc',
        
        elenco: [
            {
                nome: 'Yuri Santos',
                nick: 'yuurih',
                imagem: '',
                nomeENick: 'Yuri “yuurih” Santos',
            },
            {
                nome: 'Kaike Cerato',
                nick: 'KSCERATO',
                imagem: '',
                nomeENick: 'Kaike “KSCERATO” Cerato',
            },
            {
                nome: 'Gabriel Toledo',
                nick: 'FalleN',
                imagem: '',
                nomeENick: 'Gabriel “FalleN” Toledo',
            },
            {
                nome: 'Danil Golubenko',
                nick: 'molodoy',
                imagem: '',
                nomeENick: 'Danil “molodoy” Golubenko',
            },
            {
                nome: 'Mareks Gaļinskis',
                nick: 'YEKINDAR',
                imagem: '',
                nomeENick: 'Mareks “YEKINDAR” Gaļinskis',
            },
            {
                nome: 'Sid Macedo',
                nick: 'sidde',
                imagem: '',
                nomeENick: 'Sid “sidde” Macedo',
            },
        ],
    },
    {
        nome: 'Mibr',
        id: 'mibr',
        regiao: 'br',
        abreviacao: 'mibr',
        enderecoImagem: 'https://img-cdn.hltv.org/teamlogo/m_JQ624LNFHWiUY-25uuaE.png?ixlib=java-2.1.0&w=50&s=80a1e479dd1b15b974d3e2d5588763af',
        elenco: [
            {
                nome: 'Yuri Santos',
                nick: 'yuurih',
                imagem: '',
                nomeENick: 'Yuri “yuurih” Santos',
            },
            {
                nome: 'Kaike Cerato',
                nick: 'KSCERATO',
                imagem: '',
                nomeENick: 'Kaike “KSCERATO” Cerato',
            },
            {
                nome: 'Gabriel Toledo',
                nick: 'FalleN',
                imagem: '',
                nomeENick: 'Gabriel “FalleN” Toledo',
            },
            {
                nome: 'Danil Golubenko',
                nick: 'molodoy',
                imagem: '',
                nomeENick: 'Danil “molodoy” Golubenko',
            },
            {
                nome: 'Mareks Gaļinskis',
                nick: 'YEKINDAR',
                imagem: '',
                nomeENick: 'Mareks “YEKINDAR” Gaļinskis',
            },
            {
                nome: 'Sid Macedo',
                nick: 'sidde',
                imagem: '',
                nomeENick: 'Sid “sidde” Macedo',
            },
        ],
    },
    {
        nome: 'Legacy',
        id: 'legacy',
        regiao: 'br',
        abreviacao: 'leg',
        enderecoImagem: 'https://img-cdn.hltv.org/teamlogo/RWbHH6RA8uGwJurGeLFvSr.png?ixlib=java-2.1.0&w=100&s=10ff29ff632e0bd82922f4fcd83f930f',
        elenco: [
            {
                nome: 'Yuri Santos',
                nick: 'yuurih',
                imagem: '',
                nomeENick: 'Yuri “yuurih” Santos',
            },
            {
                nome: 'Kaike Cerato',
                nick: 'KSCERATO',
                imagem: '',
                nomeENick: 'Kaike “KSCERATO” Cerato',
            },
            {
                nome: 'Gabriel Toledo',
                nick: 'FalleN',
                imagem: '',
                nomeENick: 'Gabriel “FalleN” Toledo',
            },
            {
                nome: 'Danil Golubenko',
                nick: 'molodoy',
                imagem: '',
                nomeENick: 'Danil “molodoy” Golubenko',
            },
            {
                nome: 'Mareks Gaļinskis',
                nick: 'YEKINDAR',
                imagem: '',
                nomeENick: 'Mareks “YEKINDAR” Gaļinskis',
            },
            {
                nome: 'Sid Macedo',
                nick: 'sidde',
                imagem: '',
                nomeENick: 'Sid “sidde” Macedo',
            },
        ],
    },
    {
        nome: 'Pain',
        id: 'pain',
        regiao: 'br',
        abreviacao: 'pain',
        enderecoImagem: 'https://img-cdn.hltv.org/teamlogo/x7znFH8_QjLXOQRyR2y7Xp.png?ixlib=java-2.1.0&w=100&s=9d82f86f4573bab52b77611afcddb595',
        elenco: [
            {
                nome: 'Yuri Santos',
                nick: 'yuurih',
                imagem: '',
                nomeENick: 'Yuri “yuurih” Santos',
            },
            {
                nome: 'Kaike Cerato',
                nick: 'KSCERATO',
                imagem: '',
                nomeENick: 'Kaike “KSCERATO” Cerato',
            },
            {
                nome: 'Gabriel Toledo',
                nick: 'FalleN',
                imagem: '',
                nomeENick: 'Gabriel “FalleN” Toledo',
            },
            {
                nome: 'Danil Golubenko',
                nick: 'molodoy',
                imagem: '',
                nomeENick: 'Danil “molodoy” Golubenko',
            },
            {
                nome: 'Mareks Gaļinskis',
                nick: 'YEKINDAR',
                imagem: '',
                nomeENick: 'Mareks “YEKINDAR” Gaļinskis',
            },
            {
                nome: 'Sid Macedo',
                nick: 'sidde',
                imagem: '',
                nomeENick: 'Sid “sidde” Macedo',
            },
        ],
    },
    {
        nome: 'Oddik',
        id: 'oddik',
        regiao: 'br',
        abreviacao: 'odd',
        enderecoImagem: 'https://img-cdn.hltv.org/teamlogo/OyrfDgfALykW3zHDRh5Pnc.png?ixlib=java-2.1.0&w=50&s=f4d5734a7c6d930088fe882cbde540e6',
        elenco: [
            {
                nome: 'Yuri Santos',
                nick: 'yuurih',
                imagem: '',
                nomeENick: 'Yuri “yuurih” Santos',
            },
            {
                nome: 'Kaike Cerato',
                nick: 'KSCERATO',
                imagem: '',
                nomeENick: 'Kaike “KSCERATO” Cerato',
            },
            {
                nome: 'Gabriel Toledo',
                nick: 'FalleN',
                imagem: '',
                nomeENick: 'Gabriel “FalleN” Toledo',
            },
            {
                nome: 'Danil Golubenko',
                nick: 'molodoy',
                imagem: '',
                nomeENick: 'Danil “molodoy” Golubenko',
            },
            {
                nome: 'Mareks Gaļinskis',
                nick: 'YEKINDAR',
                imagem: '',
                nomeENick: 'Mareks “YEKINDAR” Gaļinskis',
            },
            {
                nome: 'Sid Macedo',
                nick: 'sidde',
                imagem: '',
                nomeENick: 'Sid “sidde” Macedo',
            },
        ],
    },
    {
        nome: 'Fluxo',
        id: 'fluxo',
        regiao: 'br',
        abreviacao: 'flx',
        enderecoImagem: 'https://img-cdn.hltv.org/teamlogo/zGveLNj821BCJGMu93qnj-.png?invert=true&ixlib=java-2.1.0&sat=-100&w=100&s=05ba2381b631226cb8c0a2828c357cca',
        elenco: [
            {
                nome: 'Yuri Santos',
                nick: 'yuurih',
                imagem: '',
                nomeENick: 'Yuri “yuurih” Santos',
            },
            {
                nome: 'Kaike Cerato',
                nick: 'KSCERATO',
                imagem: '',
                nomeENick: 'Kaike “KSCERATO” Cerato',
            },
            {
                nome: 'Gabriel Toledo',
                nick: 'FalleN',
                imagem: '',
                nomeENick: 'Gabriel “FalleN” Toledo',
            },
            {
                nome: 'Danil Golubenko',
                nick: 'molodoy',
                imagem: '',
                nomeENick: 'Danil “molodoy” Golubenko',
            },
            {
                nome: 'Mareks Gaļinskis',
                nick: 'YEKINDAR',
                imagem: '',
                nomeENick: 'Mareks “YEKINDAR” Gaļinskis',
            },
            {
                nome: 'Sid Macedo',
                nick: 'sidde',
                imagem: '',
                nomeENick: 'Sid “sidde” Macedo',
            },
        ],
    },
    {
        nome: 'Sharks',
        id: 'sharks',
        regiao: 'br',
        abreviacao: 'sha',
        enderecoImagem: 'https://img-cdn.hltv.org/teamlogo/xduTwTuydAWc0Dbt-eEjeH.png?ixlib=java-2.1.0&w=50&s=16cdced9e9b1a2b2e771157638f39391',
        elenco: [
            {
                nome: 'Yuri Santos',
                nick: 'yuurih',
                imagem: '',
                nomeENick: 'Yuri “yuurih” Santos',
            },
            {
                nome: 'Kaike Cerato',
                nick: 'KSCERATO',
                imagem: '',
                nomeENick: 'Kaike “KSCERATO” Cerato',
            },
            {
                nome: 'Gabriel Toledo',
                nick: 'FalleN',
                imagem: '',
                nomeENick: 'Gabriel “FalleN” Toledo',
            },
            {
                nome: 'Danil Golubenko',
                nick: 'molodoy',
                imagem: '',
                nomeENick: 'Danil “molodoy” Golubenko',
            },
            {
                nome: 'Mareks Gaļinskis',
                nick: 'YEKINDAR',
                imagem: '',
                nomeENick: 'Mareks “YEKINDAR” Gaļinskis',
            },
            {
                nome: 'Sid Macedo',
                nick: 'sidde',
                imagem: '',
                nomeENick: 'Sid “sidde” Macedo',
            },
        ],
    },
    {
        nome: '9z',
        id: '9z',
        regiao: 'br',
        abreviacao: '9z',
        enderecoImagem: 'https://img-cdn.hltv.org/teamlogo/COZDFWOIm41AT0srqOHFhM.png?ixlib=java-2.1.0&w=100&s=7a26ad9dbf9d353c92106a4f59c7d604',
        elenco: [
            {
                nome: 'Yuri Santos',
                nick: 'yuurih',
                imagem: '',
                nomeENick: 'Yuri “yuurih” Santos',
            },
            {
                nome: 'Kaike Cerato',
                nick: 'KSCERATO',
                imagem: '',
                nomeENick: 'Kaike “KSCERATO” Cerato',
            },
            {
                nome: 'Gabriel Toledo',
                nick: 'FalleN',
                imagem: '',
                nomeENick: 'Gabriel “FalleN” Toledo',
            },
            {
                nome: 'Danil Golubenko',
                nick: 'molodoy',
                imagem: '',
                nomeENick: 'Danil “molodoy” Golubenko',
            },
            {
                nome: 'Mareks Gaļinskis',
                nick: 'YEKINDAR',
                imagem: '',
                nomeENick: 'Mareks “YEKINDAR” Gaļinskis',
            },
            {
                nome: 'Sid Macedo',
                nick: 'sidde',
                imagem: '',
                nomeENick: 'Sid “sidde” Macedo',
            },
        ],
    },
    {
        nome: 'Bestia',
        id: 'bestia',
        regiao: 'br',
        abreviacao: 'bes',
        enderecoImagem: 'https://img-cdn.hltv.org/teamlogo/Z_R5K__qrvHmPjF66iCay-.png?invert=true&ixlib=java-2.1.0&sat=-100&w=100&s=89310d1e7c179ffd9fe4044db709a39c',
        elenco: [
            {
                nome: 'Yuri Santos',
                nick: 'yuurih',
                imagem: '',
                nomeENick: 'Yuri “yuurih” Santos',
            },
            {
                nome: 'Kaike Cerato',
                nick: 'KSCERATO',
                imagem: '',
                nomeENick: 'Kaike “KSCERATO” Cerato',
            },
            {
                nome: 'Gabriel Toledo',
                nick: 'FalleN',
                imagem: '',
                nomeENick: 'Gabriel “FalleN” Toledo',
            },
            {
                nome: 'Danil Golubenko',
                nick: 'molodoy',
                imagem: '',
                nomeENick: 'Danil “molodoy” Golubenko',
            },
            {
                nome: 'Mareks Gaļinskis',
                nick: 'YEKINDAR',
                imagem: '',
                nomeENick: 'Mareks “YEKINDAR” Gaļinskis',
            },
            {
                nome: 'Sid Macedo',
                nick: 'sidde',
                imagem: '',
                nomeENick: 'Sid “sidde” Macedo',
            },
        ],
    },
    {
        nome: 'Red Canids',
        id: 'redcanids',
        regiao: 'br',
        abreviacao: 'red',
        enderecoImagem: 'https://img-cdn.hltv.org/teamlogo/Lyr7VJ-litGOwnRBu_8K5q.png?ixlib=java-2.1.0&w=50&s=4beac26b74d83ad2b1753ba2c5cb575d',
        elenco: [
            {
                nome: 'Yuri Santos',
                nick: 'yuurih',
                imagem: '',
                nomeENick: 'Yuri “yuurih” Santos',
            },
            {
                nome: 'Kaike Cerato',
                nick: 'KSCERATO',
                imagem: '',
                nomeENick: 'Kaike “KSCERATO” Cerato',
            },
            {
                nome: 'Gabriel Toledo',
                nick: 'FalleN',
                imagem: '',
                nomeENick: 'Gabriel “FalleN” Toledo',
            },
            {
                nome: 'Danil Golubenko',
                nick: 'molodoy',
                imagem: '',
                nomeENick: 'Danil “molodoy” Golubenko',
            },
            {
                nome: 'Mareks Gaļinskis',
                nick: 'YEKINDAR',
                imagem: '',
                nomeENick: 'Mareks “YEKINDAR” Gaļinskis',
            },
            {
                nome: 'Sid Macedo',
                nick: 'sidde',
                imagem: '',
                nomeENick: 'Sid “sidde” Macedo',
            },
        ],
    },
    {
        nome: 'Flamengo',
        id: 'flamengo',
        regiao: 'br',
        abreviacao: 'fla',
        enderecoImagem: 'https://img-cdn.hltv.org/teamlogo/SU0UNahnVBdNkysv3rDF9S.png?ixlib=java-2.1.0&w=50&s=8c927717650b6c84b8b0f755fe925c4e',
        elenco: [
            {
                nome: 'Yuri Santos',
                nick: 'yuurih',
                imagem: '',
                nomeENick: 'Yuri “yuurih” Santos',
            },
            {
                nome: 'Kaike Cerato',
                nick: 'KSCERATO',
                imagem: '',
                nomeENick: 'Kaike “KSCERATO” Cerato',
            },
            {
                nome: 'Gabriel Toledo',
                nick: 'FalleN',
                imagem: '',
                nomeENick: 'Gabriel “FalleN” Toledo',
            },
            {
                nome: 'Danil Golubenko',
                nick: 'molodoy',
                imagem: '',
                nomeENick: 'Danil “molodoy” Golubenko',
            },
            {
                nome: 'Mareks Gaļinskis',
                nick: 'YEKINDAR',
                imagem: '',
                nomeENick: 'Mareks “YEKINDAR” Gaļinskis',
            },
            {
                nome: 'Sid Macedo',
                nick: 'sidde',
                imagem: '',
                nomeENick: 'Sid “sidde” Macedo',
            },
        ],
    },
    {
        nome: 'Faze Clan',
        id: 'fazeclan',
        regiao: 'eu',
        abreviacao: 'faze',
        enderecoImagem: 'https://img-cdn.hltv.org/teamlogo/66pHABGIztb3uoDAU18k76.png?ixlib=java-2.1.0&w=50&s=1aeaeb52d80c1f20afe885e4ddd5896c',
        elenco: [
            {
                nome: 'Yuri Santos',
                nick: 'yuurih',
                imagem: '',
                nomeENick: 'Yuri “yuurih” Santos',
            },
            {
                nome: 'Kaike Cerato',
                nick: 'KSCERATO',
                imagem: '',
                nomeENick: 'Kaike “KSCERATO” Cerato',
            },
            {
                nome: 'Gabriel Toledo',
                nick: 'FalleN',
                imagem: '',
                nomeENick: 'Gabriel “FalleN” Toledo',
            },
            {
                nome: 'Danil Golubenko',
                nick: 'molodoy',
                imagem: '',
                nomeENick: 'Danil “molodoy” Golubenko',
            },
            {
                nome: 'Mareks Gaļinskis',
                nick: 'YEKINDAR',
                imagem: '',
                nomeENick: 'Mareks “YEKINDAR” Gaļinskis',
            },
            {
                nome: 'Sid Macedo',
                nick: 'sidde',
                imagem: '',
                nomeENick: 'Sid “sidde” Macedo',
            },
        ],
    },
    {
        nome: 'Complexity',
        id: 'complexity',
        regiao: 'eu',
        abreviacao: 'col',
        enderecoImagem: 'https://img-cdn.hltv.org/teamlogo/HP3QlPseFLIDHNmZjeyA9A.png?ixlib=java-2.1.0&w=50&s=1501bcedcd47063f56d6611756d1b80a',
        elenco: [
            {
                nome: 'Yuri Santos',
                nick: 'yuurih',
                imagem: '',
                nomeENick: 'Yuri “yuurih” Santos',
            },
            {
                nome: 'Kaike Cerato',
                nick: 'KSCERATO',
                imagem: '',
                nomeENick: 'Kaike “KSCERATO” Cerato',
            },
            {
                nome: 'Gabriel Toledo',
                nick: 'FalleN',
                imagem: '',
                nomeENick: 'Gabriel “FalleN” Toledo',
            },
            {
                nome: 'Danil Golubenko',
                nick: 'molodoy',
                imagem: '',
                nomeENick: 'Danil “molodoy” Golubenko',
            },
            {
                nome: 'Mareks Gaļinskis',
                nick: 'YEKINDAR',
                imagem: '',
                nomeENick: 'Mareks “YEKINDAR” Gaļinskis',
            },
            {
                nome: 'Sid Macedo',
                nick: 'sidde',
                imagem: '',
                nomeENick: 'Sid “sidde” Macedo',
            },
        ],
    },
    {
        nome: 'Vitality',
        id: 'vitality',
        regiao: 'eu',
        abreviacao: 'vit',
        enderecoImagem: 'https://img-cdn.hltv.org/teamlogo/yeXBldn9w8LZCgdElAenPs.png?ixlib=java-2.1.0&w=50&s=15eaba0b75250065d20162d2cb05e3e6',
        elenco: [
            {
                nome: 'Yuri Santos',
                nick: 'yuurih',
                imagem: '',
                nomeENick: 'Yuri “yuurih” Santos',
            },
            {
                nome: 'Kaike Cerato',
                nick: 'KSCERATO',
                imagem: '',
                nomeENick: 'Kaike “KSCERATO” Cerato',
            },
            {
                nome: 'Gabriel Toledo',
                nick: 'FalleN',
                imagem: '',
                nomeENick: 'Gabriel “FalleN” Toledo',
            },
            {
                nome: 'Danil Golubenko',
                nick: 'molodoy',
                imagem: '',
                nomeENick: 'Danil “molodoy” Golubenko',
            },
            {
                nome: 'Mareks Gaļinskis',
                nick: 'YEKINDAR',
                imagem: '',
                nomeENick: 'Mareks “YEKINDAR” Gaļinskis',
            },
            {
                nome: 'Sid Macedo',
                nick: 'sidde',
                imagem: '',
                nomeENick: 'Sid “sidde” Macedo',
            },
        ],
    },
    {
        nome: 'Mouz',
        id: 'mouz',
        regiao: 'eu',
        abreviacao: 'mou',
        enderecoImagem: 'https://img-cdn.hltv.org/teamlogo/IejtXpquZnE8KqYPB1LNKw.svg?ixlib=java-2.1.0&s=7fd33b8def053fbfd8fdbb58e3bdcd3c',
        elenco: [
            {
                nome: 'Yuri Santos',
                nick: 'yuurih',
                imagem: '',
                nomeENick: 'Yuri “yuurih” Santos',
            },
            {
                nome: 'Kaike Cerato',
                nick: 'KSCERATO',
                imagem: '',
                nomeENick: 'Kaike “KSCERATO” Cerato',
            },
            {
                nome: 'Gabriel Toledo',
                nick: 'FalleN',
                imagem: '',
                nomeENick: 'Gabriel “FalleN” Toledo',
            },
            {
                nome: 'Danil Golubenko',
                nick: 'molodoy',
                imagem: '',
                nomeENick: 'Danil “molodoy” Golubenko',
            },
            {
                nome: 'Mareks Gaļinskis',
                nick: 'YEKINDAR',
                imagem: '',
                nomeENick: 'Mareks “YEKINDAR” Gaļinskis',
            },
            {
                nome: 'Sid Macedo',
                nick: 'sidde',
                imagem: '',
                nomeENick: 'Sid “sidde” Macedo',
            },
        ],
    },
    {
        nome: 'Spirit',
        id: 'spirit',
        regiao: 'eu',
        abreviacao: 'spi',
        enderecoImagem: 'https://img-cdn.hltv.org/teamlogo/ywdn4tmAvXfllLeV2SkkvF.png?ixlib=java-2.1.0&w=50&s=9c70c7fbb048348f70f686acd2369c58',
        elenco: [
            {
                nome: 'Yuri Santos',
                nick: 'yuurih',
                imagem: '',
                nomeENick: 'Yuri “yuurih” Santos',
            },
            {
                nome: 'Kaike Cerato',
                nick: 'KSCERATO',
                imagem: '',
                nomeENick: 'Kaike “KSCERATO” Cerato',
            },
            {
                nome: 'Gabriel Toledo',
                nick: 'FalleN',
                imagem: '',
                nomeENick: 'Gabriel “FalleN” Toledo',
            },
            {
                nome: 'Danil Golubenko',
                nick: 'molodoy',
                imagem: '',
                nomeENick: 'Danil “molodoy” Golubenko',
            },
            {
                nome: 'Mareks Gaļinskis',
                nick: 'YEKINDAR',
                imagem: '',
                nomeENick: 'Mareks “YEKINDAR” Gaļinskis',
            },
            {
                nome: 'Sid Macedo',
                nick: 'sidde',
                imagem: '',
                nomeENick: 'Sid “sidde” Macedo',
            },
        ],
    },
    {
        nome: 'Falcons',
        id: 'falcons',
        regiao: 'eu',
        abreviacao: 'fal',
        enderecoImagem: 'https://img-cdn.hltv.org/teamlogo/4eJSkDQINNM6Tbs4WvLzkN.png?ixlib=java-2.1.0&w=50&s=d8c857ea47046f61eca695beab0d12ef',
        elenco: [
            {
                nome: 'Yuri Santos',
                nick: 'yuurih',
                imagem: '',
                nomeENick: 'Yuri “yuurih” Santos',
            },
            {
                nome: 'Kaike Cerato',
                nick: 'KSCERATO',
                imagem: '',
                nomeENick: 'Kaike “KSCERATO” Cerato',
            },
            {
                nome: 'Gabriel Toledo',
                nick: 'FalleN',
                imagem: '',
                nomeENick: 'Gabriel “FalleN” Toledo',
            },
            {
                nome: 'Danil Golubenko',
                nick: 'molodoy',
                imagem: '',
                nomeENick: 'Danil “molodoy” Golubenko',
            },
            {
                nome: 'Mareks Gaļinskis',
                nick: 'YEKINDAR',
                imagem: '',
                nomeENick: 'Mareks “YEKINDAR” Gaļinskis',
            },
            {
                nome: 'Sid Macedo',
                nick: 'sidde',
                imagem: '',
                nomeENick: 'Sid “sidde” Macedo',
            },
        ],
    },
    {
        nome: 'Aurora',
        id: 'aurora',
        regiao: 'eu',
        abreviacao: 'aur',
        enderecoImagem: 'https://img-cdn.hltv.org/teamlogo/yJzPNOeXlyiniNxanYJCrv.png?ixlib=java-2.1.0&w=50&s=2c08f70c2f2f8c2024a438ddcf19bbf1',
        elenco: [
            {
                nome: 'Yuri Santos',
                nick: 'yuurih',
                imagem: '',
                nomeENick: 'Yuri “yuurih” Santos',
            },
            {
                nome: 'Kaike Cerato',
                nick: 'KSCERATO',
                imagem: '',
                nomeENick: 'Kaike “KSCERATO” Cerato',
            },
            {
                nome: 'Gabriel Toledo',
                nick: 'FalleN',
                imagem: '',
                nomeENick: 'Gabriel “FalleN” Toledo',
            },
            {
                nome: 'Danil Golubenko',
                nick: 'molodoy',
                imagem: '',
                nomeENick: 'Danil “molodoy” Golubenko',
            },
            {
                nome: 'Mareks Gaļinskis',
                nick: 'YEKINDAR',
                imagem: '',
                nomeENick: 'Mareks “YEKINDAR” Gaļinskis',
            },
            {
                nome: 'Sid Macedo',
                nick: 'sidde',
                imagem: '',
                nomeENick: 'Sid “sidde” Macedo',
            },
        ],
    },
    {
        nome: 'Natus Vincere',
        id: 'navi',
        regiao: 'eu',
        abreviacao: 'navi',
        enderecoImagem: 'https://img-cdn.hltv.org/teamlogo/9iMirAi7ArBLNU8p3kqUTZ.svg?ixlib=java-2.1.0&s=4dd8635be16122656093ae9884675d0c',
        elenco: [
            {
                nome: 'Yuri Santos',
                nick: 'yuurih',
                imagem: '',
                nomeENick: 'Yuri “yuurih” Santos',
            },
            {
                nome: 'Kaike Cerato',
                nick: 'KSCERATO',
                imagem: '',
                nomeENick: 'Kaike “KSCERATO” Cerato',
            },
            {
                nome: 'Gabriel Toledo',
                nick: 'FalleN',
                imagem: '',
                nomeENick: 'Gabriel “FalleN” Toledo',
            },
            {
                nome: 'Danil Golubenko',
                nick: 'molodoy',
                imagem: '',
                nomeENick: 'Danil “molodoy” Golubenko',
            },
            {
                nome: 'Mareks Gaļinskis',
                nick: 'YEKINDAR',
                imagem: '',
                nomeENick: 'Mareks “YEKINDAR” Gaļinskis',
            },
            {
                nome: 'Sid Macedo',
                nick: 'sidde',
                imagem: '',
                nomeENick: 'Sid “sidde” Macedo',
            },
        ],
    },
    {
        nome: 'G2',
        id: 'g2',
        regiao: 'eu',
        abreviacao: 'g2',
        enderecoImagem: 'https://img-cdn.hltv.org/teamlogo/zFLwAELOD15BjJSDMMNBWQ.png?ixlib=java-2.1.0&w=50&s=affb583e6716d8ee904826992255cc4b',
        elenco: [
            {
                nome: 'Yuri Santos',
                nick: 'yuurih',
                imagem: '',
                nomeENick: 'Yuri “yuurih” Santos',
            },
            {
                nome: 'Kaike Cerato',
                nick: 'KSCERATO',
                imagem: '',
                nomeENick: 'Kaike “KSCERATO” Cerato',
            },
            {
                nome: 'Gabriel Toledo',
                nick: 'FalleN',
                imagem: '',
                nomeENick: 'Gabriel “FalleN” Toledo',
            },
            {
                nome: 'Danil Golubenko',
                nick: 'molodoy',
                imagem: '',
                nomeENick: 'Danil “molodoy” Golubenko',
            },
            {
                nome: 'Mareks Gaļinskis',
                nick: 'YEKINDAR',
                imagem: '',
                nomeENick: 'Mareks “YEKINDAR” Gaļinskis',
            },
            {
                nome: 'Sid Macedo',
                nick: 'sidde',
                imagem: '',
                nomeENick: 'Sid “sidde” Macedo',
            },
        ],
    },
    {
        nome: 'Virtus Pro',
        id: 'virtuspro',
        regiao: 'eu',
        abreviacao: 'vp',
        enderecoImagem: 'https://img-cdn.hltv.org/teamlogo/yZ6Bpuui1rW3jocXQ68XgZ.svg?ixlib=java-2.1.0&s=f39be1d3e7baf30a4e7f0b1216720875',
        elenco: [
            {
                nome: 'Yuri Santos',
                nick: 'yuurih',
                imagem: '',
                nomeENick: 'Yuri “yuurih” Santos',
            },
            {
                nome: 'Kaike Cerato',
                nick: 'KSCERATO',
                imagem: '',
                nomeENick: 'Kaike “KSCERATO” Cerato',
            },
            {
                nome: 'Gabriel Toledo',
                nick: 'FalleN',
                imagem: '',
                nomeENick: 'Gabriel “FalleN” Toledo',
            },
            {
                nome: 'Danil Golubenko',
                nick: 'molodoy',
                imagem: '',
                nomeENick: 'Danil “molodoy” Golubenko',
            },
            {
                nome: 'Mareks Gaļinskis',
                nick: 'YEKINDAR',
                imagem: '',
                nomeENick: 'Mareks “YEKINDAR” Gaļinskis',
            },
            {
                nome: 'Sid Macedo',
                nick: 'sidde',
                imagem: '',
                nomeENick: 'Sid “sidde” Macedo',
            },
        ],
    },
    {
        nome: 'Astralis',
        id: 'astralis',
        regiao: 'eu',
        abreviacao: 'ast',
        enderecoImagem: 'https://img-cdn.hltv.org/teamlogo/9bgXHp-oh1oaXr7F0mTGmd.svg?ixlib=java-2.1.0&s=f567161ab183001be33948b98c4b2067',
        elenco: [
            {
                nome: 'Yuri Santos',
                nick: 'yuurih',
                imagem: '',
                nomeENick: 'Yuri “yuurih” Santos',
            },
            {
                nome: 'Kaike Cerato',
                nick: 'KSCERATO',
                imagem: '',
                nomeENick: 'Kaike “KSCERATO” Cerato',
            },
            {
                nome: 'Gabriel Toledo',
                nick: 'FalleN',
                imagem: '',
                nomeENick: 'Gabriel “FalleN” Toledo',
            },
            {
                nome: 'Danil Golubenko',
                nick: 'molodoy',
                imagem: '',
                nomeENick: 'Danil “molodoy” Golubenko',
            },
            {
                nome: 'Mareks Gaļinskis',
                nick: 'YEKINDAR',
                imagem: '',
                nomeENick: 'Mareks “YEKINDAR” Gaļinskis',
            },
            {
                nome: 'Sid Macedo',
                nick: 'sidde',
                imagem: '',
                nomeENick: 'Sid “sidde” Macedo',
            },
        ],
    },
    {
        nome: 'Heroic',
        id: 'heroic',
        regiao: 'eu',
        abreviacao: 'her',
        enderecoImagem: 'https://img-cdn.hltv.org/teamlogo/4S22uk_gnZTiQiI-hhH4yp.png?ixlib=java-2.1.0&w=50&s=3619ddf1d490573ab3dc261b8c2f3f6f',
        elenco: [
            {
                nome: 'Yuri Santos',
                nick: 'yuurih',
                imagem: '',
                nomeENick: 'Yuri “yuurih” Santos',
            },
            {
                nome: 'Kaike Cerato',
                nick: 'KSCERATO',
                imagem: '',
                nomeENick: 'Kaike “KSCERATO” Cerato',
            },
            {
                nome: 'Gabriel Toledo',
                nick: 'FalleN',
                imagem: '',
                nomeENick: 'Gabriel “FalleN” Toledo',
            },
            {
                nome: 'Danil Golubenko',
                nick: 'molodoy',
                imagem: '',
                nomeENick: 'Danil “molodoy” Golubenko',
            },
            {
                nome: 'Mareks Gaļinskis',
                nick: 'YEKINDAR',
                imagem: '',
                nomeENick: 'Mareks “YEKINDAR” Gaļinskis',
            },
            {
                nome: 'Sid Macedo',
                nick: 'sidde',
                imagem: '',
                nomeENick: 'Sid “sidde” Macedo',
            },
        ],
    },
    {
        nome: 'Ninjas in Pyjamas',
        id: 'ninjasinpyjamas',
        regiao: 'eu',
        abreviacao: 'nip',
        enderecoImagem: 'https://img-cdn.hltv.org/teamlogo/mbY2YeFKUAbL9NyO6ab7-c.png?ixlib=java-2.1.0&w=50&s=33901dc1e88dc81e479574095806fcb9',
        elenco: [
            {
                nome: 'Yuri Santos',
                nick: 'yuurih',
                imagem: '',
                nomeENick: 'Yuri “yuurih” Santos',
            },
            {
                nome: 'Kaike Cerato',
                nick: 'KSCERATO',
                imagem: '',
                nomeENick: 'Kaike “KSCERATO” Cerato',
            },
            {
                nome: 'Gabriel Toledo',
                nick: 'FalleN',
                imagem: '',
                nomeENick: 'Gabriel “FalleN” Toledo',
            },
            {
                nome: 'Danil Golubenko',
                nick: 'molodoy',
                imagem: '',
                nomeENick: 'Danil “molodoy” Golubenko',
            },
            {
                nome: 'Mareks Gaļinskis',
                nick: 'YEKINDAR',
                imagem: '',
                nomeENick: 'Mareks “YEKINDAR” Gaļinskis',
            },
            {
                nome: 'Sid Macedo',
                nick: 'sidde',
                imagem: '',
                nomeENick: 'Sid “sidde” Macedo',
            },
        ],
    },
    {
        nome: 'Fnatic',
        id: 'fnatic',
        regiao: 'eu',
        abreviacao: 'fnt',
        enderecoImagem: 'https://img-cdn.hltv.org/teamlogo/dLtWEdSV58lIX1amAFggy0.svg?ixlib=java-2.1.0&s=f24d0a7b3ef24ed57184a51d35202b4e',
        elenco: [
            {
                nome: 'Yuri Santos',
                nick: 'yuurih',
                imagem: '',
                nomeENick: 'Yuri “yuurih” Santos',
            },
            {
                nome: 'Kaike Cerato',
                nick: 'KSCERATO',
                imagem: '',
                nomeENick: 'Kaike “KSCERATO” Cerato',
            },
            {
                nome: 'Gabriel Toledo',
                nick: 'FalleN',
                imagem: '',
                nomeENick: 'Gabriel “FalleN” Toledo',
            },
            {
                nome: 'Danil Golubenko',
                nick: 'molodoy',
                imagem: '',
                nomeENick: 'Danil “molodoy” Golubenko',
            },
            {
                nome: 'Mareks Gaļinskis',
                nick: 'YEKINDAR',
                imagem: '',
                nomeENick: 'Mareks “YEKINDAR” Gaļinskis',
            },
            {
                nome: 'Sid Macedo',
                nick: 'sidde',
                imagem: '',
                nomeENick: 'Sid “sidde” Macedo',
            },
        ],
    },
    {
        nome: 'Saw',
        id: 'saw',
        regiao: 'eu',
        abreviacao: 'saw',
        enderecoImagem: 'https://img-cdn.hltv.org/teamlogo/9vOlYp2U_z0vXPb9aLK-4r.png?invert=true&ixlib=java-2.1.0&sat=-100&w=50&s=6013ee655368f0f1a69cd0c2183ba332',
        elenco: [
            {
                nome: 'Yuri Santos',
                nick: 'yuurih',
                imagem: '',
                nomeENick: 'Yuri “yuurih” Santos',
            },
            {
                nome: 'Kaike Cerato',
                nick: 'KSCERATO',
                imagem: '',
                nomeENick: 'Kaike “KSCERATO” Cerato',
            },
            {
                nome: 'Gabriel Toledo',
                nick: 'FalleN',
                imagem: '',
                nomeENick: 'Gabriel “FalleN” Toledo',
            },
            {
                nome: 'Danil Golubenko',
                nick: 'molodoy',
                imagem: '',
                nomeENick: 'Danil “molodoy” Golubenko',
            },
            {
                nome: 'Mareks Gaļinskis',
                nick: 'YEKINDAR',
                imagem: '',
                nomeENick: 'Mareks “YEKINDAR” Gaļinskis',
            },
            {
                nome: 'Sid Macedo',
                nick: 'sidde',
                imagem: '',
                nomeENick: 'Sid “sidde” Macedo',
            },
        ],
    },
    {
        nome: 'Liquid',
        id: 'liquid',
        regiao: 'eu',
        abreviacao: 'liq',
        enderecoImagem: 'https://img-cdn.hltv.org/teamlogo/JMeLLbWKCIEJrmfPaqOz4O.svg?ixlib=java-2.1.0&s=c02caf90234d3a3ebac074c84ba1ea62',
        elenco: [
            {
                nome: 'Yuri Santos',
                nick: 'yuurih',
                imagem: '',
                nomeENick: 'Yuri “yuurih” Santos',
            },
            {
                nome: 'Kaike Cerato',
                nick: 'KSCERATO',
                imagem: '',
                nomeENick: 'Kaike “KSCERATO” Cerato',
            },
            {
                nome: 'Gabriel Toledo',
                nick: 'FalleN',
                imagem: '',
                nomeENick: 'Gabriel “FalleN” Toledo',
            },
            {
                nome: 'Danil Golubenko',
                nick: 'molodoy',
                imagem: '',
                nomeENick: 'Danil “molodoy” Golubenko',
            },
            {
                nome: 'Mareks Gaļinskis',
                nick: 'YEKINDAR',
                imagem: '',
                nomeENick: 'Mareks “YEKINDAR” Gaļinskis',
            },
            {
                nome: 'Sid Macedo',
                nick: 'sidde',
                imagem: '',
                nomeENick: 'Sid “sidde” Macedo',
            },
        ],
    },
]

export default clubesDoCoracao